; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                  = 7160929-64-bit MS Windows           
[ DataSettings ]
datatype                             = snNucleotide                        
containsCodingNuc                    = False                               
MissingBaseSymbol                    = ?                                   
IdenticalBaseSymbol                  = .                                   
GapSymbol                            = -                                   
[ ProcessTypes ]
ppRelTimeML                          = true                                
[ AnalysisSettings ]
Analysis                             = Estimate Divergence Times (ML)      
Tree to Use                          = Use tree from file                  
Clock Settings                       = ====================                
Clock Type                           = Local clocks                        
Variance Estimation Method           = Analytical method                   
No. of Bootstrap Replications        = Not Applicable                      
Statistical Method                   = Maximum Likelihood                  
Substitution Model                   = ====================                
Substitutions Type                   = Nucleotide                          
Model/Method                         = General Time Reversible model       
Rates and Patterns                   = ====================                
Rates among Sites                    = Gamma Distributed (G)               
No of Discrete Gamma Categories      = 5                                   
Data Subset to Use                   = ====================                
Gaps/Missing Data Treatment          = Pairwise deletion                   
Site Coverage Cutoff (%)             = Not Applicable                      
Branch Swap Filter                   = None                                
System Resource Usage                = ====================                
Number of Threads                    = 1                                   
Has Time Limit                       = False                               
Maximum Execution Time               = -1                                  
